# Generated by Django 6.0.4 on 2026-05-27 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0002_alter_appeal_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeal',
            options={'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения'},
        ),
        migrations.AlterModelOptions(
            name='appealhistory',
            options={'verbose_name': 'История изменений', 'verbose_name_plural': 'История изменений'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterField(
            model_name='appeal',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appeals.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='deadline',
            field=models.DateTimeField(verbose_name='Срок исполнения'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='iin',
            field=models.CharField(max_length=12, verbose_name='ИИН'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appeals.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='text',
            field=models.TextField(verbose_name='Текст обращения'),
        ),
        migrations.AlterField(
            model_name='appealhistory',
            name='appeal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appeals.appeal', verbose_name='Обращение'),
        ),
        migrations.AlterField(
            model_name='appealhistory',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='appealhistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
        migrations.AlterField(
            model_name='appealhistory',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='appealhistory',
            name='new_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_status', to='appeals.status', verbose_name='Новый статус'),
        ),
        migrations.AlterField(
            model_name='appealhistory',
            name='old_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_status', to='appeals.status', verbose_name='Старый статус'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
